// megafunction wizard: %Shift register (RAM-based)%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: ALTSHIFT_TAPS 

// ============================================================
// File Name: buffer_IP_640.v
// Megafunction Name(s):
// 			ALTSHIFT_TAPS
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 25.1std.0 Build 1129 10/21/2025 SC Lite Edition
// ************************************************************


//Copyright (C) 2025  Altera Corporation. All rights reserved.
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and any partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, the Altera Quartus Prime License Agreement,
//the Altera IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Altera and sold by Altera or its authorized distributors.  Please
//refer to the Altera Software License Subscription Agreements 
//on the Quartus Prime software download page.


//altshift_taps DEVICE_FAMILY="Cyclone V" NUMBER_OF_TAPS=1 RAM_BLOCK_TYPE="AUTO" TAP_DISTANCE=640 WIDTH=12 aclr clken clock shiftin shiftout taps INTENDED_DEVICE_FAMILY="Cyclone V" lpm_hint="RAM_BLOCK_TYPE=AUTO"
//VERSION_BEGIN 25.1 cbx_altdpram 2025:10:22:10:31:27:SC cbx_altera_counter 2025:10:22:10:31:27:SC cbx_altera_syncram 2025:10:22:10:31:27:SC cbx_altera_syncram_nd_impl 2025:10:22:10:31:27:SC cbx_altshift_taps 2025:10:22:10:31:26:SC cbx_altsyncram 2025:10:22:10:31:27:SC cbx_cycloneii 2025:10:22:10:31:27:SC cbx_lpm_add_sub 2025:10:22:10:31:27:SC cbx_lpm_compare 2025:10:22:10:31:27:SC cbx_lpm_counter 2025:10:22:10:31:27:SC cbx_lpm_decode 2025:10:22:10:31:27:SC cbx_lpm_mux 2025:10:22:10:31:26:SC cbx_mgl 2025:10:22:10:31:44:SC cbx_nadder 2025:10:22:10:31:27:SC cbx_stratix 2025:10:22:10:31:27:SC cbx_stratixii 2025:10:22:10:31:26:SC cbx_stratixiii 2025:10:22:10:31:27:SC cbx_stratixv 2025:10:22:10:31:26:SC cbx_util_mgl 2025:10:22:10:31:27:SC  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//altsyncram ADDRESS_REG_B="CLOCK0" DEVICE_FAMILY="Cyclone V" NUMWORDS_A=638 NUMWORDS_B=638 OPERATION_MODE="DUAL_PORT" OUTDATA_ACLR_B="CLEAR0" OUTDATA_REG_B="CLOCK0" RAM_BLOCK_TYPE="AUTO" READ_DURING_WRITE_MODE_MIXED_PORTS="OLD_DATA" WIDTH_A=12 WIDTH_B=12 WIDTH_BYTEENA_A=1 WIDTHAD_A=10 WIDTHAD_B=10 aclr0 address_a address_b clock0 clocken0 data_a q_b wren_a
//VERSION_BEGIN 25.1 cbx_altera_syncram_nd_impl 2025:10:22:10:31:27:SC cbx_altsyncram 2025:10:22:10:31:27:SC cbx_cycloneii 2025:10:22:10:31:27:SC cbx_lpm_add_sub 2025:10:22:10:31:27:SC cbx_lpm_compare 2025:10:22:10:31:27:SC cbx_lpm_decode 2025:10:22:10:31:27:SC cbx_lpm_mux 2025:10:22:10:31:26:SC cbx_mgl 2025:10:22:10:31:44:SC cbx_nadder 2025:10:22:10:31:27:SC cbx_stratix 2025:10:22:10:31:27:SC cbx_stratixii 2025:10:22:10:31:26:SC cbx_stratixiii 2025:10:22:10:31:27:SC cbx_stratixv 2025:10:22:10:31:26:SC cbx_util_mgl 2025:10:22:10:31:27:SC  VERSION_END

//synthesis_resources = M10K 2 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  buffer_IP_640_altsyncram
	( 
	aclr0,
	address_a,
	address_b,
	clock0,
	clocken0,
	data_a,
	q_b,
	wren_a) /* synthesis synthesis_clearbox=1 */;
	input   aclr0;
	input   [9:0]  address_a;
	input   [9:0]  address_b;
	input   clock0;
	input   clocken0;
	input   [11:0]  data_a;
	output   [11:0]  q_b;
	input   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr0;
	tri1   [9:0]  address_b;
	tri1   clock0;
	tri1   clocken0;
	tri1   [11:0]  data_a;
	tri0   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block5a_0portbdataout;
	wire  [0:0]   wire_ram_block5a_1portbdataout;
	wire  [0:0]   wire_ram_block5a_2portbdataout;
	wire  [0:0]   wire_ram_block5a_3portbdataout;
	wire  [0:0]   wire_ram_block5a_4portbdataout;
	wire  [0:0]   wire_ram_block5a_5portbdataout;
	wire  [0:0]   wire_ram_block5a_6portbdataout;
	wire  [0:0]   wire_ram_block5a_7portbdataout;
	wire  [0:0]   wire_ram_block5a_8portbdataout;
	wire  [0:0]   wire_ram_block5a_9portbdataout;
	wire  [0:0]   wire_ram_block5a_10portbdataout;
	wire  [0:0]   wire_ram_block5a_11portbdataout;
	wire  [9:0]  address_a_wire;
	wire  [9:0]  address_b_wire;

	cyclonev_ram_block   ram_block5a_0
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[0]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_0portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_0.clk0_core_clock_enable = "ena0",
		ram_block5a_0.clk0_input_clock_enable = "ena0",
		ram_block5a_0.clk0_output_clock_enable = "ena0",
		ram_block5a_0.connectivity_checking = "OFF",
		ram_block5a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_0.mixed_port_feed_through_mode = "old",
		ram_block5a_0.operation_mode = "dual_port",
		ram_block5a_0.port_a_address_width = 10,
		ram_block5a_0.port_a_data_width = 1,
		ram_block5a_0.port_a_first_address = 0,
		ram_block5a_0.port_a_first_bit_number = 0,
		ram_block5a_0.port_a_last_address = 637,
		ram_block5a_0.port_a_logical_ram_depth = 638,
		ram_block5a_0.port_a_logical_ram_width = 12,
		ram_block5a_0.port_b_address_clear = "none",
		ram_block5a_0.port_b_address_clock = "clock0",
		ram_block5a_0.port_b_address_width = 10,
		ram_block5a_0.port_b_data_out_clear = "clear0",
		ram_block5a_0.port_b_data_out_clock = "clock0",
		ram_block5a_0.port_b_data_width = 1,
		ram_block5a_0.port_b_first_address = 0,
		ram_block5a_0.port_b_first_bit_number = 0,
		ram_block5a_0.port_b_last_address = 637,
		ram_block5a_0.port_b_logical_ram_depth = 638,
		ram_block5a_0.port_b_logical_ram_width = 12,
		ram_block5a_0.port_b_read_enable_clock = "clock0",
		ram_block5a_0.ram_block_type = "AUTO",
		ram_block5a_0.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_1
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[1]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_1portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_1.clk0_core_clock_enable = "ena0",
		ram_block5a_1.clk0_input_clock_enable = "ena0",
		ram_block5a_1.clk0_output_clock_enable = "ena0",
		ram_block5a_1.connectivity_checking = "OFF",
		ram_block5a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_1.mixed_port_feed_through_mode = "old",
		ram_block5a_1.operation_mode = "dual_port",
		ram_block5a_1.port_a_address_width = 10,
		ram_block5a_1.port_a_data_width = 1,
		ram_block5a_1.port_a_first_address = 0,
		ram_block5a_1.port_a_first_bit_number = 1,
		ram_block5a_1.port_a_last_address = 637,
		ram_block5a_1.port_a_logical_ram_depth = 638,
		ram_block5a_1.port_a_logical_ram_width = 12,
		ram_block5a_1.port_b_address_clear = "none",
		ram_block5a_1.port_b_address_clock = "clock0",
		ram_block5a_1.port_b_address_width = 10,
		ram_block5a_1.port_b_data_out_clear = "clear0",
		ram_block5a_1.port_b_data_out_clock = "clock0",
		ram_block5a_1.port_b_data_width = 1,
		ram_block5a_1.port_b_first_address = 0,
		ram_block5a_1.port_b_first_bit_number = 1,
		ram_block5a_1.port_b_last_address = 637,
		ram_block5a_1.port_b_logical_ram_depth = 638,
		ram_block5a_1.port_b_logical_ram_width = 12,
		ram_block5a_1.port_b_read_enable_clock = "clock0",
		ram_block5a_1.ram_block_type = "AUTO",
		ram_block5a_1.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_2
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[2]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_2portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_2.clk0_core_clock_enable = "ena0",
		ram_block5a_2.clk0_input_clock_enable = "ena0",
		ram_block5a_2.clk0_output_clock_enable = "ena0",
		ram_block5a_2.connectivity_checking = "OFF",
		ram_block5a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_2.mixed_port_feed_through_mode = "old",
		ram_block5a_2.operation_mode = "dual_port",
		ram_block5a_2.port_a_address_width = 10,
		ram_block5a_2.port_a_data_width = 1,
		ram_block5a_2.port_a_first_address = 0,
		ram_block5a_2.port_a_first_bit_number = 2,
		ram_block5a_2.port_a_last_address = 637,
		ram_block5a_2.port_a_logical_ram_depth = 638,
		ram_block5a_2.port_a_logical_ram_width = 12,
		ram_block5a_2.port_b_address_clear = "none",
		ram_block5a_2.port_b_address_clock = "clock0",
		ram_block5a_2.port_b_address_width = 10,
		ram_block5a_2.port_b_data_out_clear = "clear0",
		ram_block5a_2.port_b_data_out_clock = "clock0",
		ram_block5a_2.port_b_data_width = 1,
		ram_block5a_2.port_b_first_address = 0,
		ram_block5a_2.port_b_first_bit_number = 2,
		ram_block5a_2.port_b_last_address = 637,
		ram_block5a_2.port_b_logical_ram_depth = 638,
		ram_block5a_2.port_b_logical_ram_width = 12,
		ram_block5a_2.port_b_read_enable_clock = "clock0",
		ram_block5a_2.ram_block_type = "AUTO",
		ram_block5a_2.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_3
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[3]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_3portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_3.clk0_core_clock_enable = "ena0",
		ram_block5a_3.clk0_input_clock_enable = "ena0",
		ram_block5a_3.clk0_output_clock_enable = "ena0",
		ram_block5a_3.connectivity_checking = "OFF",
		ram_block5a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_3.mixed_port_feed_through_mode = "old",
		ram_block5a_3.operation_mode = "dual_port",
		ram_block5a_3.port_a_address_width = 10,
		ram_block5a_3.port_a_data_width = 1,
		ram_block5a_3.port_a_first_address = 0,
		ram_block5a_3.port_a_first_bit_number = 3,
		ram_block5a_3.port_a_last_address = 637,
		ram_block5a_3.port_a_logical_ram_depth = 638,
		ram_block5a_3.port_a_logical_ram_width = 12,
		ram_block5a_3.port_b_address_clear = "none",
		ram_block5a_3.port_b_address_clock = "clock0",
		ram_block5a_3.port_b_address_width = 10,
		ram_block5a_3.port_b_data_out_clear = "clear0",
		ram_block5a_3.port_b_data_out_clock = "clock0",
		ram_block5a_3.port_b_data_width = 1,
		ram_block5a_3.port_b_first_address = 0,
		ram_block5a_3.port_b_first_bit_number = 3,
		ram_block5a_3.port_b_last_address = 637,
		ram_block5a_3.port_b_logical_ram_depth = 638,
		ram_block5a_3.port_b_logical_ram_width = 12,
		ram_block5a_3.port_b_read_enable_clock = "clock0",
		ram_block5a_3.ram_block_type = "AUTO",
		ram_block5a_3.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_4
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[4]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_4portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_4.clk0_core_clock_enable = "ena0",
		ram_block5a_4.clk0_input_clock_enable = "ena0",
		ram_block5a_4.clk0_output_clock_enable = "ena0",
		ram_block5a_4.connectivity_checking = "OFF",
		ram_block5a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_4.mixed_port_feed_through_mode = "old",
		ram_block5a_4.operation_mode = "dual_port",
		ram_block5a_4.port_a_address_width = 10,
		ram_block5a_4.port_a_data_width = 1,
		ram_block5a_4.port_a_first_address = 0,
		ram_block5a_4.port_a_first_bit_number = 4,
		ram_block5a_4.port_a_last_address = 637,
		ram_block5a_4.port_a_logical_ram_depth = 638,
		ram_block5a_4.port_a_logical_ram_width = 12,
		ram_block5a_4.port_b_address_clear = "none",
		ram_block5a_4.port_b_address_clock = "clock0",
		ram_block5a_4.port_b_address_width = 10,
		ram_block5a_4.port_b_data_out_clear = "clear0",
		ram_block5a_4.port_b_data_out_clock = "clock0",
		ram_block5a_4.port_b_data_width = 1,
		ram_block5a_4.port_b_first_address = 0,
		ram_block5a_4.port_b_first_bit_number = 4,
		ram_block5a_4.port_b_last_address = 637,
		ram_block5a_4.port_b_logical_ram_depth = 638,
		ram_block5a_4.port_b_logical_ram_width = 12,
		ram_block5a_4.port_b_read_enable_clock = "clock0",
		ram_block5a_4.ram_block_type = "AUTO",
		ram_block5a_4.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_5
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[5]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_5portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_5.clk0_core_clock_enable = "ena0",
		ram_block5a_5.clk0_input_clock_enable = "ena0",
		ram_block5a_5.clk0_output_clock_enable = "ena0",
		ram_block5a_5.connectivity_checking = "OFF",
		ram_block5a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_5.mixed_port_feed_through_mode = "old",
		ram_block5a_5.operation_mode = "dual_port",
		ram_block5a_5.port_a_address_width = 10,
		ram_block5a_5.port_a_data_width = 1,
		ram_block5a_5.port_a_first_address = 0,
		ram_block5a_5.port_a_first_bit_number = 5,
		ram_block5a_5.port_a_last_address = 637,
		ram_block5a_5.port_a_logical_ram_depth = 638,
		ram_block5a_5.port_a_logical_ram_width = 12,
		ram_block5a_5.port_b_address_clear = "none",
		ram_block5a_5.port_b_address_clock = "clock0",
		ram_block5a_5.port_b_address_width = 10,
		ram_block5a_5.port_b_data_out_clear = "clear0",
		ram_block5a_5.port_b_data_out_clock = "clock0",
		ram_block5a_5.port_b_data_width = 1,
		ram_block5a_5.port_b_first_address = 0,
		ram_block5a_5.port_b_first_bit_number = 5,
		ram_block5a_5.port_b_last_address = 637,
		ram_block5a_5.port_b_logical_ram_depth = 638,
		ram_block5a_5.port_b_logical_ram_width = 12,
		ram_block5a_5.port_b_read_enable_clock = "clock0",
		ram_block5a_5.ram_block_type = "AUTO",
		ram_block5a_5.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_6
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[6]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_6portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_6.clk0_core_clock_enable = "ena0",
		ram_block5a_6.clk0_input_clock_enable = "ena0",
		ram_block5a_6.clk0_output_clock_enable = "ena0",
		ram_block5a_6.connectivity_checking = "OFF",
		ram_block5a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_6.mixed_port_feed_through_mode = "old",
		ram_block5a_6.operation_mode = "dual_port",
		ram_block5a_6.port_a_address_width = 10,
		ram_block5a_6.port_a_data_width = 1,
		ram_block5a_6.port_a_first_address = 0,
		ram_block5a_6.port_a_first_bit_number = 6,
		ram_block5a_6.port_a_last_address = 637,
		ram_block5a_6.port_a_logical_ram_depth = 638,
		ram_block5a_6.port_a_logical_ram_width = 12,
		ram_block5a_6.port_b_address_clear = "none",
		ram_block5a_6.port_b_address_clock = "clock0",
		ram_block5a_6.port_b_address_width = 10,
		ram_block5a_6.port_b_data_out_clear = "clear0",
		ram_block5a_6.port_b_data_out_clock = "clock0",
		ram_block5a_6.port_b_data_width = 1,
		ram_block5a_6.port_b_first_address = 0,
		ram_block5a_6.port_b_first_bit_number = 6,
		ram_block5a_6.port_b_last_address = 637,
		ram_block5a_6.port_b_logical_ram_depth = 638,
		ram_block5a_6.port_b_logical_ram_width = 12,
		ram_block5a_6.port_b_read_enable_clock = "clock0",
		ram_block5a_6.ram_block_type = "AUTO",
		ram_block5a_6.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_7
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[7]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_7portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_7.clk0_core_clock_enable = "ena0",
		ram_block5a_7.clk0_input_clock_enable = "ena0",
		ram_block5a_7.clk0_output_clock_enable = "ena0",
		ram_block5a_7.connectivity_checking = "OFF",
		ram_block5a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_7.mixed_port_feed_through_mode = "old",
		ram_block5a_7.operation_mode = "dual_port",
		ram_block5a_7.port_a_address_width = 10,
		ram_block5a_7.port_a_data_width = 1,
		ram_block5a_7.port_a_first_address = 0,
		ram_block5a_7.port_a_first_bit_number = 7,
		ram_block5a_7.port_a_last_address = 637,
		ram_block5a_7.port_a_logical_ram_depth = 638,
		ram_block5a_7.port_a_logical_ram_width = 12,
		ram_block5a_7.port_b_address_clear = "none",
		ram_block5a_7.port_b_address_clock = "clock0",
		ram_block5a_7.port_b_address_width = 10,
		ram_block5a_7.port_b_data_out_clear = "clear0",
		ram_block5a_7.port_b_data_out_clock = "clock0",
		ram_block5a_7.port_b_data_width = 1,
		ram_block5a_7.port_b_first_address = 0,
		ram_block5a_7.port_b_first_bit_number = 7,
		ram_block5a_7.port_b_last_address = 637,
		ram_block5a_7.port_b_logical_ram_depth = 638,
		ram_block5a_7.port_b_logical_ram_width = 12,
		ram_block5a_7.port_b_read_enable_clock = "clock0",
		ram_block5a_7.ram_block_type = "AUTO",
		ram_block5a_7.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_8
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[8]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_8portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_8.clk0_core_clock_enable = "ena0",
		ram_block5a_8.clk0_input_clock_enable = "ena0",
		ram_block5a_8.clk0_output_clock_enable = "ena0",
		ram_block5a_8.connectivity_checking = "OFF",
		ram_block5a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_8.mixed_port_feed_through_mode = "old",
		ram_block5a_8.operation_mode = "dual_port",
		ram_block5a_8.port_a_address_width = 10,
		ram_block5a_8.port_a_data_width = 1,
		ram_block5a_8.port_a_first_address = 0,
		ram_block5a_8.port_a_first_bit_number = 8,
		ram_block5a_8.port_a_last_address = 637,
		ram_block5a_8.port_a_logical_ram_depth = 638,
		ram_block5a_8.port_a_logical_ram_width = 12,
		ram_block5a_8.port_b_address_clear = "none",
		ram_block5a_8.port_b_address_clock = "clock0",
		ram_block5a_8.port_b_address_width = 10,
		ram_block5a_8.port_b_data_out_clear = "clear0",
		ram_block5a_8.port_b_data_out_clock = "clock0",
		ram_block5a_8.port_b_data_width = 1,
		ram_block5a_8.port_b_first_address = 0,
		ram_block5a_8.port_b_first_bit_number = 8,
		ram_block5a_8.port_b_last_address = 637,
		ram_block5a_8.port_b_logical_ram_depth = 638,
		ram_block5a_8.port_b_logical_ram_width = 12,
		ram_block5a_8.port_b_read_enable_clock = "clock0",
		ram_block5a_8.ram_block_type = "AUTO",
		ram_block5a_8.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_9
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[9]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_9portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_9.clk0_core_clock_enable = "ena0",
		ram_block5a_9.clk0_input_clock_enable = "ena0",
		ram_block5a_9.clk0_output_clock_enable = "ena0",
		ram_block5a_9.connectivity_checking = "OFF",
		ram_block5a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_9.mixed_port_feed_through_mode = "old",
		ram_block5a_9.operation_mode = "dual_port",
		ram_block5a_9.port_a_address_width = 10,
		ram_block5a_9.port_a_data_width = 1,
		ram_block5a_9.port_a_first_address = 0,
		ram_block5a_9.port_a_first_bit_number = 9,
		ram_block5a_9.port_a_last_address = 637,
		ram_block5a_9.port_a_logical_ram_depth = 638,
		ram_block5a_9.port_a_logical_ram_width = 12,
		ram_block5a_9.port_b_address_clear = "none",
		ram_block5a_9.port_b_address_clock = "clock0",
		ram_block5a_9.port_b_address_width = 10,
		ram_block5a_9.port_b_data_out_clear = "clear0",
		ram_block5a_9.port_b_data_out_clock = "clock0",
		ram_block5a_9.port_b_data_width = 1,
		ram_block5a_9.port_b_first_address = 0,
		ram_block5a_9.port_b_first_bit_number = 9,
		ram_block5a_9.port_b_last_address = 637,
		ram_block5a_9.port_b_logical_ram_depth = 638,
		ram_block5a_9.port_b_logical_ram_width = 12,
		ram_block5a_9.port_b_read_enable_clock = "clock0",
		ram_block5a_9.ram_block_type = "AUTO",
		ram_block5a_9.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_10
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[10]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_10portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_10.clk0_core_clock_enable = "ena0",
		ram_block5a_10.clk0_input_clock_enable = "ena0",
		ram_block5a_10.clk0_output_clock_enable = "ena0",
		ram_block5a_10.connectivity_checking = "OFF",
		ram_block5a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_10.mixed_port_feed_through_mode = "old",
		ram_block5a_10.operation_mode = "dual_port",
		ram_block5a_10.port_a_address_width = 10,
		ram_block5a_10.port_a_data_width = 1,
		ram_block5a_10.port_a_first_address = 0,
		ram_block5a_10.port_a_first_bit_number = 10,
		ram_block5a_10.port_a_last_address = 637,
		ram_block5a_10.port_a_logical_ram_depth = 638,
		ram_block5a_10.port_a_logical_ram_width = 12,
		ram_block5a_10.port_b_address_clear = "none",
		ram_block5a_10.port_b_address_clock = "clock0",
		ram_block5a_10.port_b_address_width = 10,
		ram_block5a_10.port_b_data_out_clear = "clear0",
		ram_block5a_10.port_b_data_out_clock = "clock0",
		ram_block5a_10.port_b_data_width = 1,
		ram_block5a_10.port_b_first_address = 0,
		ram_block5a_10.port_b_first_bit_number = 10,
		ram_block5a_10.port_b_last_address = 637,
		ram_block5a_10.port_b_logical_ram_depth = 638,
		ram_block5a_10.port_b_logical_ram_width = 12,
		ram_block5a_10.port_b_read_enable_clock = "clock0",
		ram_block5a_10.ram_block_type = "AUTO",
		ram_block5a_10.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block5a_11
	( 
	.clk0(clock0),
	.clr0(aclr0),
	.dftout(),
	.eccstatus(),
	.ena0(clocken0),
	.portaaddr({address_a_wire[9:0]}),
	.portadatain({data_a[11]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[9:0]}),
	.portbdataout(wire_ram_block5a_11portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block5a_11.clk0_core_clock_enable = "ena0",
		ram_block5a_11.clk0_input_clock_enable = "ena0",
		ram_block5a_11.clk0_output_clock_enable = "ena0",
		ram_block5a_11.connectivity_checking = "OFF",
		ram_block5a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block5a_11.mixed_port_feed_through_mode = "old",
		ram_block5a_11.operation_mode = "dual_port",
		ram_block5a_11.port_a_address_width = 10,
		ram_block5a_11.port_a_data_width = 1,
		ram_block5a_11.port_a_first_address = 0,
		ram_block5a_11.port_a_first_bit_number = 11,
		ram_block5a_11.port_a_last_address = 637,
		ram_block5a_11.port_a_logical_ram_depth = 638,
		ram_block5a_11.port_a_logical_ram_width = 12,
		ram_block5a_11.port_b_address_clear = "none",
		ram_block5a_11.port_b_address_clock = "clock0",
		ram_block5a_11.port_b_address_width = 10,
		ram_block5a_11.port_b_data_out_clear = "clear0",
		ram_block5a_11.port_b_data_out_clock = "clock0",
		ram_block5a_11.port_b_data_width = 1,
		ram_block5a_11.port_b_first_address = 0,
		ram_block5a_11.port_b_first_bit_number = 11,
		ram_block5a_11.port_b_last_address = 637,
		ram_block5a_11.port_b_logical_ram_depth = 638,
		ram_block5a_11.port_b_logical_ram_width = 12,
		ram_block5a_11.port_b_read_enable_clock = "clock0",
		ram_block5a_11.ram_block_type = "AUTO",
		ram_block5a_11.lpm_type = "cyclonev_ram_block";
	assign
		address_a_wire = address_a,
		address_b_wire = address_b,
		q_b = {wire_ram_block5a_11portbdataout[0], wire_ram_block5a_10portbdataout[0], wire_ram_block5a_9portbdataout[0], wire_ram_block5a_8portbdataout[0], wire_ram_block5a_7portbdataout[0], wire_ram_block5a_6portbdataout[0], wire_ram_block5a_5portbdataout[0], wire_ram_block5a_4portbdataout[0], wire_ram_block5a_3portbdataout[0], wire_ram_block5a_2portbdataout[0], wire_ram_block5a_1portbdataout[0], wire_ram_block5a_0portbdataout[0]};
endmodule //buffer_IP_640_altsyncram


//lpm_counter DEVICE_FAMILY="Cyclone V" lpm_direction="UP" lpm_modulus=638 lpm_port_updown="PORT_UNUSED" lpm_width=10 clk_en clock q
//VERSION_BEGIN 25.1 cbx_cycloneii 2025:10:22:10:31:27:SC cbx_lpm_add_sub 2025:10:22:10:31:27:SC cbx_lpm_compare 2025:10:22:10:31:27:SC cbx_lpm_counter 2025:10:22:10:31:27:SC cbx_lpm_decode 2025:10:22:10:31:27:SC cbx_mgl 2025:10:22:10:31:44:SC cbx_nadder 2025:10:22:10:31:27:SC cbx_stratix 2025:10:22:10:31:27:SC cbx_stratixii 2025:10:22:10:31:26:SC  VERSION_END


//lpm_compare DEVICE_FAMILY="Cyclone V" LPM_WIDTH=10 ONE_INPUT_IS_CONSTANT="YES" aeb dataa datab
//VERSION_BEGIN 25.1 cbx_cycloneii 2025:10:22:10:31:27:SC cbx_lpm_add_sub 2025:10:22:10:31:27:SC cbx_lpm_compare 2025:10:22:10:31:27:SC cbx_mgl 2025:10:22:10:31:44:SC cbx_nadder 2025:10:22:10:31:27:SC cbx_stratix 2025:10:22:10:31:27:SC cbx_stratixii 2025:10:22:10:31:26:SC  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  buffer_IP_640_cmpr
	( 
	aeb,
	dataa,
	datab) /* synthesis synthesis_clearbox=1 */;
	output   aeb;
	input   [9:0]  dataa;
	input   [9:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [9:0]  dataa;
	tri0   [9:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  aeb_result_wire;
	wire  [0:0]  aneb_result_wire;
	wire  [26:0]  data_wire;
	wire  eq_wire;

	assign
		aeb = eq_wire,
		aeb_result_wire = (~ aneb_result_wire),
		aneb_result_wire = (data_wire[0] | data_wire[1]),
		data_wire = {datab[9], dataa[9], datab[8], dataa[8], datab[7], dataa[7], datab[6], dataa[6], datab[5], dataa[5], datab[4], dataa[4], datab[3], dataa[3], datab[2], dataa[2], datab[1], dataa[1], datab[0], dataa[0], ((data_wire[23] ^ data_wire[24]) | (data_wire[25] ^ data_wire[26])), ((data_wire[19] ^ data_wire[20]) | (data_wire[21] ^ data_wire[22])), ((data_wire[15] ^ data_wire[16]) | (data_wire[17] ^ data_wire[18])), ((data_wire[11] ^ data_wire[12]) | (data_wire[13] ^ data_wire[14])), ((data_wire[7] ^ data_wire[8]) | (data_wire[9] ^ data_wire[10])), data_wire[6], (((data_wire[2] | data_wire[3]) | data_wire[4]) | data_wire[5])},
		eq_wire = aeb_result_wire;
endmodule //buffer_IP_640_cmpr

//synthesis_resources = lut 10 reg 10 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  buffer_IP_640_cntr
	( 
	clk_en,
	clock,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clk_en;
	input   clock;
	output   [9:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clk_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire	[9:0]	wire_counter_reg_bit_d;
	wire	[9:0]	wire_counter_reg_bit_asdata;
	reg	[9:0]	counter_reg_bit;
	wire	[9:0]	wire_counter_reg_bit_ena;
	wire	[9:0]	wire_counter_reg_bit_sload;
	wire  wire_cmpr6_aeb;
	wire  [0:0]   wire_counter_comb_bita_0cout;
	wire  [0:0]   wire_counter_comb_bita_1cout;
	wire  [0:0]   wire_counter_comb_bita_2cout;
	wire  [0:0]   wire_counter_comb_bita_3cout;
	wire  [0:0]   wire_counter_comb_bita_4cout;
	wire  [0:0]   wire_counter_comb_bita_5cout;
	wire  [0:0]   wire_counter_comb_bita_6cout;
	wire  [0:0]   wire_counter_comb_bita_7cout;
	wire  [0:0]   wire_counter_comb_bita_8cout;
	wire  [0:0]   wire_counter_comb_bita_9cout;
	wire  [0:0]   wire_counter_comb_bita_0sumout;
	wire  [0:0]   wire_counter_comb_bita_1sumout;
	wire  [0:0]   wire_counter_comb_bita_2sumout;
	wire  [0:0]   wire_counter_comb_bita_3sumout;
	wire  [0:0]   wire_counter_comb_bita_4sumout;
	wire  [0:0]   wire_counter_comb_bita_5sumout;
	wire  [0:0]   wire_counter_comb_bita_6sumout;
	wire  [0:0]   wire_counter_comb_bita_7sumout;
	wire  [0:0]   wire_counter_comb_bita_8sumout;
	wire  [0:0]   wire_counter_comb_bita_9sumout;
	wire  aclr_actual;
	wire cnt_en;
	wire  compare_result;
	wire  cout_actual;
	wire [9:0]  data;
	wire  external_cin;
	wire  lsb_cin;
	wire  [9:0]  modulus_bus;
	wire  modulus_trigger;
	wire  [9:0]  s_val;
	wire  [9:0]  safe_q;
	wire sclr;
	wire sload;
	wire sset;
	wire  time_to_clear;
	wire  updown_dir;
	wire  updown_lsb;
	wire  updown_other_bits;

	// synopsys translate_off
	initial
		counter_reg_bit[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[0:0] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[0:0] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[0:0] <= 1'b0;
			else if (wire_counter_reg_bit_sload[0:0] == 1'b1) counter_reg_bit[0:0] <= wire_counter_reg_bit_asdata[0:0];
			else  counter_reg_bit[0:0] <= wire_counter_reg_bit_d[0:0];
	// synopsys translate_off
	initial
		counter_reg_bit[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[1:1] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[1:1] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[1:1] <= 1'b0;
			else if (wire_counter_reg_bit_sload[1:1] == 1'b1) counter_reg_bit[1:1] <= wire_counter_reg_bit_asdata[1:1];
			else  counter_reg_bit[1:1] <= wire_counter_reg_bit_d[1:1];
	// synopsys translate_off
	initial
		counter_reg_bit[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[2:2] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[2:2] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[2:2] <= 1'b0;
			else if (wire_counter_reg_bit_sload[2:2] == 1'b1) counter_reg_bit[2:2] <= wire_counter_reg_bit_asdata[2:2];
			else  counter_reg_bit[2:2] <= wire_counter_reg_bit_d[2:2];
	// synopsys translate_off
	initial
		counter_reg_bit[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[3:3] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[3:3] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[3:3] <= 1'b0;
			else if (wire_counter_reg_bit_sload[3:3] == 1'b1) counter_reg_bit[3:3] <= wire_counter_reg_bit_asdata[3:3];
			else  counter_reg_bit[3:3] <= wire_counter_reg_bit_d[3:3];
	// synopsys translate_off
	initial
		counter_reg_bit[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[4:4] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[4:4] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[4:4] <= 1'b0;
			else if (wire_counter_reg_bit_sload[4:4] == 1'b1) counter_reg_bit[4:4] <= wire_counter_reg_bit_asdata[4:4];
			else  counter_reg_bit[4:4] <= wire_counter_reg_bit_d[4:4];
	// synopsys translate_off
	initial
		counter_reg_bit[5:5] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[5:5] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[5:5] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[5:5] <= 1'b0;
			else if (wire_counter_reg_bit_sload[5:5] == 1'b1) counter_reg_bit[5:5] <= wire_counter_reg_bit_asdata[5:5];
			else  counter_reg_bit[5:5] <= wire_counter_reg_bit_d[5:5];
	// synopsys translate_off
	initial
		counter_reg_bit[6:6] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[6:6] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[6:6] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[6:6] <= 1'b0;
			else if (wire_counter_reg_bit_sload[6:6] == 1'b1) counter_reg_bit[6:6] <= wire_counter_reg_bit_asdata[6:6];
			else  counter_reg_bit[6:6] <= wire_counter_reg_bit_d[6:6];
	// synopsys translate_off
	initial
		counter_reg_bit[7:7] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[7:7] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[7:7] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[7:7] <= 1'b0;
			else if (wire_counter_reg_bit_sload[7:7] == 1'b1) counter_reg_bit[7:7] <= wire_counter_reg_bit_asdata[7:7];
			else  counter_reg_bit[7:7] <= wire_counter_reg_bit_d[7:7];
	// synopsys translate_off
	initial
		counter_reg_bit[8:8] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[8:8] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[8:8] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[8:8] <= 1'b0;
			else if (wire_counter_reg_bit_sload[8:8] == 1'b1) counter_reg_bit[8:8] <= wire_counter_reg_bit_asdata[8:8];
			else  counter_reg_bit[8:8] <= wire_counter_reg_bit_d[8:8];
	// synopsys translate_off
	initial
		counter_reg_bit[9:9] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[9:9] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[9:9] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[9:9] <= 1'b0;
			else if (wire_counter_reg_bit_sload[9:9] == 1'b1) counter_reg_bit[9:9] <= wire_counter_reg_bit_asdata[9:9];
			else  counter_reg_bit[9:9] <= wire_counter_reg_bit_d[9:9];
	assign
		wire_counter_reg_bit_asdata = (({10{sset}} & s_val) | ({10{(~ sset)}} & (({10{sload}} & data) | (({10{(~ sload)}} & modulus_bus) & {10{(~ updown_dir)}})))),
		wire_counter_reg_bit_d = {wire_counter_comb_bita_9sumout[0:0], wire_counter_comb_bita_8sumout[0:0], wire_counter_comb_bita_7sumout[0:0], wire_counter_comb_bita_6sumout[0:0], wire_counter_comb_bita_5sumout[0:0], wire_counter_comb_bita_4sumout[0:0], wire_counter_comb_bita_3sumout[0:0], wire_counter_comb_bita_2sumout[0:0], wire_counter_comb_bita_1sumout[0:0], wire_counter_comb_bita_0sumout[0:0]};
	assign
		wire_counter_reg_bit_ena = {10{(clk_en & (((cnt_en | sclr) | sset) | sload))}},
		wire_counter_reg_bit_sload = {10{((sset | sload) | modulus_trigger)}};
	buffer_IP_640_cmpr   cmpr6
	( 
	.aeb(wire_cmpr6_aeb),
	.dataa(safe_q),
	.datab(modulus_bus));
	cyclonev_lcell_comb   counter_comb_bita_0
	( 
	.cin(lsb_cin),
	.combout(),
	.cout(wire_counter_comb_bita_0cout[0:0]),
	.datad(counter_reg_bit[0]),
	.dataf(updown_lsb),
	.shareout(),
	.sumout(wire_counter_comb_bita_0sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_0.extended_lut = "off",
		counter_comb_bita_0.lut_mask = 64'h000000000000FF00,
		counter_comb_bita_0.shared_arith = "off",
		counter_comb_bita_0.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_1
	( 
	.cin(wire_counter_comb_bita_0cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_1cout[0:0]),
	.datad(counter_reg_bit[1]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_1sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_1.extended_lut = "off",
		counter_comb_bita_1.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_1.shared_arith = "off",
		counter_comb_bita_1.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_2
	( 
	.cin(wire_counter_comb_bita_1cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_2cout[0:0]),
	.datad(counter_reg_bit[2]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_2sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_2.extended_lut = "off",
		counter_comb_bita_2.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_2.shared_arith = "off",
		counter_comb_bita_2.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_3
	( 
	.cin(wire_counter_comb_bita_2cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_3cout[0:0]),
	.datad(counter_reg_bit[3]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_3sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_3.extended_lut = "off",
		counter_comb_bita_3.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_3.shared_arith = "off",
		counter_comb_bita_3.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_4
	( 
	.cin(wire_counter_comb_bita_3cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_4cout[0:0]),
	.datad(counter_reg_bit[4]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_4sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_4.extended_lut = "off",
		counter_comb_bita_4.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_4.shared_arith = "off",
		counter_comb_bita_4.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_5
	( 
	.cin(wire_counter_comb_bita_4cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_5cout[0:0]),
	.datad(counter_reg_bit[5]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_5sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_5.extended_lut = "off",
		counter_comb_bita_5.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_5.shared_arith = "off",
		counter_comb_bita_5.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_6
	( 
	.cin(wire_counter_comb_bita_5cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_6cout[0:0]),
	.datad(counter_reg_bit[6]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_6sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_6.extended_lut = "off",
		counter_comb_bita_6.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_6.shared_arith = "off",
		counter_comb_bita_6.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_7
	( 
	.cin(wire_counter_comb_bita_6cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_7cout[0:0]),
	.datad(counter_reg_bit[7]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_7sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_7.extended_lut = "off",
		counter_comb_bita_7.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_7.shared_arith = "off",
		counter_comb_bita_7.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_8
	( 
	.cin(wire_counter_comb_bita_7cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_8cout[0:0]),
	.datad(counter_reg_bit[8]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_8sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_8.extended_lut = "off",
		counter_comb_bita_8.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_8.shared_arith = "off",
		counter_comb_bita_8.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_9
	( 
	.cin(wire_counter_comb_bita_8cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_9cout[0:0]),
	.datad(counter_reg_bit[9]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_9sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_9.extended_lut = "off",
		counter_comb_bita_9.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_9.shared_arith = "off",
		counter_comb_bita_9.lpm_type = "cyclonev_lcell_comb";
	assign
		aclr_actual = 1'b0,
		cnt_en = 1'b1,
		compare_result = wire_cmpr6_aeb,
		cout_actual = (((~ wire_counter_comb_bita_9cout[0:0]) ^ updown_other_bits) | (time_to_clear & updown_dir)),
		data = {10{1'b0}},
		external_cin = 1'b1,
		lsb_cin = 1'b0,
		modulus_bus = 10'b1001111101,
		modulus_trigger = cout_actual,
		q = safe_q,
		s_val = {10{1'b1}},
		safe_q = counter_reg_bit,
		sclr = 1'b0,
		sload = 1'b0,
		sset = 1'b0,
		time_to_clear = compare_result,
		updown_dir = 1'b1,
		updown_lsb = updown_dir,
		updown_other_bits = ((~ external_cin) | updown_dir);
endmodule //buffer_IP_640_cntr


//lpm_counter DEVICE_FAMILY="Cyclone V" lpm_avalue=638 lpm_direction="DOWN" lpm_port_updown="PORT_UNUSED" lpm_width=10 aset clk_en clock cnt_en cout
//VERSION_BEGIN 25.1 cbx_cycloneii 2025:10:22:10:31:27:SC cbx_lpm_add_sub 2025:10:22:10:31:27:SC cbx_lpm_compare 2025:10:22:10:31:27:SC cbx_lpm_counter 2025:10:22:10:31:27:SC cbx_lpm_decode 2025:10:22:10:31:27:SC cbx_mgl 2025:10:22:10:31:44:SC cbx_nadder 2025:10:22:10:31:27:SC cbx_stratix 2025:10:22:10:31:27:SC cbx_stratixii 2025:10:22:10:31:26:SC  VERSION_END

//synthesis_resources = lut 10 reg 10 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"{-to counter_reg_bit[1]} POWER_UP_LEVEL=HIGH;{-to counter_reg_bit[2]} POWER_UP_LEVEL=HIGH;{-to counter_reg_bit[3]} POWER_UP_LEVEL=HIGH;{-to counter_reg_bit[4]} POWER_UP_LEVEL=HIGH;{-to counter_reg_bit[5]} POWER_UP_LEVEL=HIGH;{-to counter_reg_bit[6]} POWER_UP_LEVEL=HIGH;{-to counter_reg_bit[9]} POWER_UP_LEVEL=HIGH"} *)
module  buffer_IP_640_cntr1
	( 
	aset,
	clk_en,
	clock,
	cnt_en,
	cout) /* synthesis synthesis_clearbox=1 */;
	input   aset;
	input   clk_en;
	input   clock;
	input   cnt_en;
	output   cout;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aset;
	tri1   clk_en;
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire	[9:0]	wire_counter_reg_bit_d;
	wire	[9:0]	wire_counter_reg_bit_asdata;
	reg	[9:0]	counter_reg_bit;
	wire	[9:0]	wire_counter_reg_bit_ena;
	wire	[9:0]	wire_counter_reg_bit_sload;
	wire  [0:0]   wire_counter_comb_bita_0cout;
	wire  [0:0]   wire_counter_comb_bita_1cout;
	wire  [0:0]   wire_counter_comb_bita_2cout;
	wire  [0:0]   wire_counter_comb_bita_3cout;
	wire  [0:0]   wire_counter_comb_bita_4cout;
	wire  [0:0]   wire_counter_comb_bita_5cout;
	wire  [0:0]   wire_counter_comb_bita_6cout;
	wire  [0:0]   wire_counter_comb_bita_7cout;
	wire  [0:0]   wire_counter_comb_bita_8cout;
	wire  [0:0]   wire_counter_comb_bita_9cout;
	wire  [0:0]   wire_counter_comb_bita_0sumout;
	wire  [0:0]   wire_counter_comb_bita_1sumout;
	wire  [0:0]   wire_counter_comb_bita_2sumout;
	wire  [0:0]   wire_counter_comb_bita_3sumout;
	wire  [0:0]   wire_counter_comb_bita_4sumout;
	wire  [0:0]   wire_counter_comb_bita_5sumout;
	wire  [0:0]   wire_counter_comb_bita_6sumout;
	wire  [0:0]   wire_counter_comb_bita_7sumout;
	wire  [0:0]   wire_counter_comb_bita_8sumout;
	wire  [0:0]   wire_counter_comb_bita_9sumout;
	wire  cout_actual;
	wire [9:0]  data;
	wire  external_cin;
	wire  lsb_cin;
	wire  [9:0]  s_val;
	wire sclr;
	wire sload;
	wire sset;
	wire  time_to_clear;
	wire  updown_dir;
	wire  updown_lsb;
	wire  updown_other_bits;

	// synopsys translate_off
	initial
		counter_reg_bit[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[0:0] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[0:0] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[0:0] <= 1'b0;
			else if (wire_counter_reg_bit_sload[0:0] == 1'b1) counter_reg_bit[0:0] <= wire_counter_reg_bit_asdata[0:0];
			else  counter_reg_bit[0:0] <= wire_counter_reg_bit_d[0:0];
	// synopsys translate_off
	initial
		counter_reg_bit[1:1] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[1:1] <= {1{1'b1}};
		else if  (wire_counter_reg_bit_ena[1:1] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[1:1] <= 1'b0;
			else if (wire_counter_reg_bit_sload[1:1] == 1'b1) counter_reg_bit[1:1] <= wire_counter_reg_bit_asdata[1:1];
			else  counter_reg_bit[1:1] <= wire_counter_reg_bit_d[1:1];
	// synopsys translate_off
	initial
		counter_reg_bit[2:2] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[2:2] <= {1{1'b1}};
		else if  (wire_counter_reg_bit_ena[2:2] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[2:2] <= 1'b0;
			else if (wire_counter_reg_bit_sload[2:2] == 1'b1) counter_reg_bit[2:2] <= wire_counter_reg_bit_asdata[2:2];
			else  counter_reg_bit[2:2] <= wire_counter_reg_bit_d[2:2];
	// synopsys translate_off
	initial
		counter_reg_bit[3:3] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[3:3] <= {1{1'b1}};
		else if  (wire_counter_reg_bit_ena[3:3] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[3:3] <= 1'b0;
			else if (wire_counter_reg_bit_sload[3:3] == 1'b1) counter_reg_bit[3:3] <= wire_counter_reg_bit_asdata[3:3];
			else  counter_reg_bit[3:3] <= wire_counter_reg_bit_d[3:3];
	// synopsys translate_off
	initial
		counter_reg_bit[4:4] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[4:4] <= {1{1'b1}};
		else if  (wire_counter_reg_bit_ena[4:4] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[4:4] <= 1'b0;
			else if (wire_counter_reg_bit_sload[4:4] == 1'b1) counter_reg_bit[4:4] <= wire_counter_reg_bit_asdata[4:4];
			else  counter_reg_bit[4:4] <= wire_counter_reg_bit_d[4:4];
	// synopsys translate_off
	initial
		counter_reg_bit[5:5] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[5:5] <= {1{1'b1}};
		else if  (wire_counter_reg_bit_ena[5:5] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[5:5] <= 1'b0;
			else if (wire_counter_reg_bit_sload[5:5] == 1'b1) counter_reg_bit[5:5] <= wire_counter_reg_bit_asdata[5:5];
			else  counter_reg_bit[5:5] <= wire_counter_reg_bit_d[5:5];
	// synopsys translate_off
	initial
		counter_reg_bit[6:6] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[6:6] <= {1{1'b1}};
		else if  (wire_counter_reg_bit_ena[6:6] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[6:6] <= 1'b0;
			else if (wire_counter_reg_bit_sload[6:6] == 1'b1) counter_reg_bit[6:6] <= wire_counter_reg_bit_asdata[6:6];
			else  counter_reg_bit[6:6] <= wire_counter_reg_bit_d[6:6];
	// synopsys translate_off
	initial
		counter_reg_bit[7:7] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[7:7] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[7:7] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[7:7] <= 1'b0;
			else if (wire_counter_reg_bit_sload[7:7] == 1'b1) counter_reg_bit[7:7] <= wire_counter_reg_bit_asdata[7:7];
			else  counter_reg_bit[7:7] <= wire_counter_reg_bit_d[7:7];
	// synopsys translate_off
	initial
		counter_reg_bit[8:8] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[8:8] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[8:8] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[8:8] <= 1'b0;
			else if (wire_counter_reg_bit_sload[8:8] == 1'b1) counter_reg_bit[8:8] <= wire_counter_reg_bit_asdata[8:8];
			else  counter_reg_bit[8:8] <= wire_counter_reg_bit_d[8:8];
	// synopsys translate_off
	initial
		counter_reg_bit[9:9] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[9:9] <= {1{1'b1}};
		else if  (wire_counter_reg_bit_ena[9:9] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[9:9] <= 1'b0;
			else if (wire_counter_reg_bit_sload[9:9] == 1'b1) counter_reg_bit[9:9] <= wire_counter_reg_bit_asdata[9:9];
			else  counter_reg_bit[9:9] <= wire_counter_reg_bit_d[9:9];
	assign
		wire_counter_reg_bit_ena = {10{(clk_en & (((cnt_en | sclr) | sset) | sload))}},
		wire_counter_reg_bit_sload = {10{(sset | sload)}},
		wire_counter_reg_bit_asdata = (({10{sset}} & s_val) | ({10{(~ sset)}} & data)),
		wire_counter_reg_bit_d = {wire_counter_comb_bita_9sumout[0:0], wire_counter_comb_bita_8sumout[0:0], wire_counter_comb_bita_7sumout[0:0], wire_counter_comb_bita_6sumout[0:0], wire_counter_comb_bita_5sumout[0:0], wire_counter_comb_bita_4sumout[0:0], wire_counter_comb_bita_3sumout[0:0], wire_counter_comb_bita_2sumout[0:0], wire_counter_comb_bita_1sumout[0:0], wire_counter_comb_bita_0sumout[0:0]};
	cyclonev_lcell_comb   counter_comb_bita_0
	( 
	.cin(lsb_cin),
	.combout(),
	.cout(wire_counter_comb_bita_0cout[0:0]),
	.datad(counter_reg_bit[0]),
	.dataf(updown_lsb),
	.shareout(),
	.sumout(wire_counter_comb_bita_0sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_0.extended_lut = "off",
		counter_comb_bita_0.lut_mask = 64'h000000000000FF00,
		counter_comb_bita_0.shared_arith = "off",
		counter_comb_bita_0.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_1
	( 
	.cin(wire_counter_comb_bita_0cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_1cout[0:0]),
	.datad(counter_reg_bit[1]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_1sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_1.extended_lut = "off",
		counter_comb_bita_1.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_1.shared_arith = "off",
		counter_comb_bita_1.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_2
	( 
	.cin(wire_counter_comb_bita_1cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_2cout[0:0]),
	.datad(counter_reg_bit[2]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_2sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_2.extended_lut = "off",
		counter_comb_bita_2.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_2.shared_arith = "off",
		counter_comb_bita_2.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_3
	( 
	.cin(wire_counter_comb_bita_2cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_3cout[0:0]),
	.datad(counter_reg_bit[3]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_3sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_3.extended_lut = "off",
		counter_comb_bita_3.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_3.shared_arith = "off",
		counter_comb_bita_3.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_4
	( 
	.cin(wire_counter_comb_bita_3cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_4cout[0:0]),
	.datad(counter_reg_bit[4]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_4sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_4.extended_lut = "off",
		counter_comb_bita_4.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_4.shared_arith = "off",
		counter_comb_bita_4.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_5
	( 
	.cin(wire_counter_comb_bita_4cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_5cout[0:0]),
	.datad(counter_reg_bit[5]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_5sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_5.extended_lut = "off",
		counter_comb_bita_5.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_5.shared_arith = "off",
		counter_comb_bita_5.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_6
	( 
	.cin(wire_counter_comb_bita_5cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_6cout[0:0]),
	.datad(counter_reg_bit[6]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_6sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_6.extended_lut = "off",
		counter_comb_bita_6.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_6.shared_arith = "off",
		counter_comb_bita_6.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_7
	( 
	.cin(wire_counter_comb_bita_6cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_7cout[0:0]),
	.datad(counter_reg_bit[7]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_7sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_7.extended_lut = "off",
		counter_comb_bita_7.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_7.shared_arith = "off",
		counter_comb_bita_7.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_8
	( 
	.cin(wire_counter_comb_bita_7cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_8cout[0:0]),
	.datad(counter_reg_bit[8]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_8sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_8.extended_lut = "off",
		counter_comb_bita_8.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_8.shared_arith = "off",
		counter_comb_bita_8.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_9
	( 
	.cin(wire_counter_comb_bita_8cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_9cout[0:0]),
	.datad(counter_reg_bit[9]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_9sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_9.extended_lut = "off",
		counter_comb_bita_9.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_9.shared_arith = "off",
		counter_comb_bita_9.lpm_type = "cyclonev_lcell_comb";
	assign
		cout = cout_actual,
		cout_actual = (((~ wire_counter_comb_bita_9cout[0:0]) ^ updown_other_bits) | (time_to_clear & updown_dir)),
		data = {10{1'b0}},
		external_cin = 1'b1,
		lsb_cin = 1'b0,
		s_val = {10{1'b1}},
		sclr = 1'b0,
		sload = 1'b0,
		sset = 1'b0,
		time_to_clear = 1'b0,
		updown_dir = 1'b0,
		updown_lsb = updown_dir,
		updown_other_bits = ((~ external_cin) | updown_dir);
endmodule //buffer_IP_640_cntr1

//synthesis_resources = lut 20 M10K 2 reg 21 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  buffer_IP_640_shift_taps
	( 
	aclr,
	clken,
	clock,
	shiftin,
	shiftout,
	taps) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clken;
	input   clock;
	input   [11:0]  shiftin;
	output   [11:0]  shiftout;
	output   [11:0]  taps;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   clken;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [11:0]   wire_altsyncram2_q_b;
	reg	dffe4;
	wire  [9:0]   wire_cntr1_q;
	wire  wire_cntr3_cout;

	buffer_IP_640_altsyncram   altsyncram2
	( 
	.aclr0(dffe4),
	.address_a(wire_cntr1_q),
	.address_b(wire_cntr1_q),
	.clock0(clock),
	.clocken0(clken),
	.data_a({shiftin}),
	.q_b(wire_altsyncram2_q_b),
	.wren_a(1'b1));
	// synopsys translate_off
	initial
		dffe4 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) dffe4 <= {1{1'b1}};
		else if  (clken == 1'b1)   dffe4 <= (~ wire_cntr3_cout);
	buffer_IP_640_cntr   cntr1
	( 
	.clk_en(clken),
	.clock(clock),
	.q(wire_cntr1_q));
	buffer_IP_640_cntr1   cntr3
	( 
	.aset(aclr),
	.clk_en(clken),
	.clock(clock),
	.cnt_en((~ wire_cntr3_cout)),
	.cout(wire_cntr3_cout));
	assign
		shiftout = wire_altsyncram2_q_b[11:0],
		taps = wire_altsyncram2_q_b;
endmodule //buffer_IP_640_shift_taps
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module buffer_IP_640 (
	aclr,
	clken,
	clock,
	shiftin,
	shiftout,
	taps)/* synthesis synthesis_clearbox = 1 */;

	input	  aclr;
	input	  clken;
	input	  clock;
	input	[11:0]  shiftin;
	output	[11:0]  shiftout;
	output	[11:0]  taps;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  aclr;
	tri1	  clken;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [11:0] sub_wire0;
	wire [11:0] sub_wire1;
	wire [11:0] shiftout = sub_wire0[11:0];
	wire [11:0] taps = sub_wire1[11:0];

	buffer_IP_640_shift_taps	buffer_IP_640_shift_taps_component (
				.aclr (aclr),
				.clken (clken),
				.clock (clock),
				.shiftin (shiftin),
				.shiftout (sub_wire0),
				.taps (sub_wire1));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ACLR NUMERIC "1"
// Retrieval info: PRIVATE: CLKEN NUMERIC "1"
// Retrieval info: PRIVATE: GROUP_TAPS NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: PRIVATE: NUMBER_OF_TAPS NUMERIC "1"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "3"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: TAP_DISTANCE NUMERIC "640"
// Retrieval info: PRIVATE: WIDTH NUMERIC "12"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: CONSTANT: LPM_HINT STRING "RAM_BLOCK_TYPE=AUTO"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altshift_taps"
// Retrieval info: CONSTANT: NUMBER_OF_TAPS NUMERIC "1"
// Retrieval info: CONSTANT: TAP_DISTANCE NUMERIC "640"
// Retrieval info: CONSTANT: WIDTH NUMERIC "12"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT VCC "aclr"
// Retrieval info: USED_PORT: clken 0 0 0 0 INPUT VCC "clken"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT NODEFVAL "clock"
// Retrieval info: USED_PORT: shiftin 0 0 12 0 INPUT NODEFVAL "shiftin[11..0]"
// Retrieval info: USED_PORT: shiftout 0 0 12 0 OUTPUT NODEFVAL "shiftout[11..0]"
// Retrieval info: USED_PORT: taps 0 0 12 0 OUTPUT NODEFVAL "taps[11..0]"
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: CONNECT: @clken 0 0 0 0 clken 0 0 0 0
// Retrieval info: CONNECT: @clock 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: @shiftin 0 0 12 0 shiftin 0 0 12 0
// Retrieval info: CONNECT: shiftout 0 0 12 0 @shiftout 0 0 12 0
// Retrieval info: CONNECT: taps 0 0 12 0 @taps 0 0 12 0
// Retrieval info: GEN_FILE: TYPE_NORMAL buffer_IP_640.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL buffer_IP_640.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL buffer_IP_640.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL buffer_IP_640.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL buffer_IP_640_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL buffer_IP_640_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL buffer_IP_640_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
